# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peoplenum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labid', models.IntegerField()),
                ('time_now', models.IntegerField()),
                ('p_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hongwai',
            name='time',
            field=models.IntegerField(),
        ),
    ]
