# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20171203_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='indooractivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labid', models.IntegerField()),
                ('time_now', models.IntegerField()),
                ('p_num', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='peoplenum',
            old_name='labid',
            new_name='indoor',
        ),
        migrations.RenameField(
            model_name='peoplenum',
            old_name='time_now',
            new_name='outdoor',
        ),
    ]
